# Generated by Django 2.2.7 on 2019-11-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=500)),
                ('film_genre', models.CharField(max_length=100)),
                ('film_logo', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=500)),
                ('series_genre', models.CharField(max_length=100)),
                ('series_logo', models.CharField(max_length=10000)),
            ],
        ),
    ]
