# Generated by Django 2.2.7 on 2019-11-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20191116_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
