# Generated by Django 2.2.7 on 2020-01-24 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_auto_20200124_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='film_played',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.Film'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='series_played',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.Series'),
        ),
    ]
