# Generated by Django 2.2.7 on 2020-01-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_auto_20200124_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='film_played',
            field=models.ManyToManyField(null=True, to='films.Film'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='series_played',
            field=models.ManyToManyField(null=True, to='films.Series'),
        ),
    ]
